/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.czytelnyblog.view;

import com.czytelnyblog.model.Person;

/**
 *
 * @author Michał Chwedczuk <czytelnyblog.wordpress.com>
 */
public class SubformView extends javax.swing.JFrame {
    private Person person;

    public SubformView(Person person) {
        this.person = person;
        initComponents();
    }

    public Person getPerson() {
        return person;
    }

        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel1 = new javax.swing.JLabel();
        lblPersonName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Swing data binding demo - SubformView");
        getContentPane().setLayout(new java.awt.FlowLayout());

        jLabel1.setText("The person is:");
        getContentPane().add(jLabel1);

        lblPersonName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${person.name}"), lblPersonName, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(lblPersonName);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblPersonName;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
